spring:
  jackson:
    time-zone:America/Sao_Paulo
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 100
    locations: classpath:db/migration

  application:
    name: cortaFila

  datasource:
    url: jdbc:mysql://localhost:3306/corta_fila
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo

logging:
  level:
    org.springframework.security: DEBUG

api:
  security:
    token:
      secret: "my-key-to-test"

twilio:
  account-sid: ${twilio-sid}
  auth-token: ${twilio-token}
  phone-number: ${twilio-phone}
